DROP TABLE IF EXISTS mock_data;

CREATE TABLE mock_data (
    id SERIAL,
    customer_first_name VARCHAR(100),
    customer_last_name VARCHAR(100),
    customer_age INT,
    customer_email VARCHAR(150),
    customer_country VARCHAR(100),
    customer_postal_code VARCHAR(20),
    customer_pet_type VARCHAR(50),
    customer_pet_name VARCHAR(100),
    customer_pet_breed VARCHAR(100),
    seller_first_name VARCHAR(100),
    seller_last_name VARCHAR(100),
    seller_email VARCHAR(150),
    seller_country VARCHAR(100),
    seller_postal_code VARCHAR(20),
    product_name VARCHAR(200),
    product_category VARCHAR(100),
    product_price NUMERIC(12,2),
    product_quantity INT,
    sale_date VARCHAR(50),
    sale_customer_id INT,
    sale_seller_id INT,
    sale_product_id INT,
    sale_quantity INT,
    sale_total_price NUMERIC(12,2),
    store_name VARCHAR(150),
    store_location VARCHAR(200),
    store_city VARCHAR(100),
    store_state VARCHAR(100),
    store_country VARCHAR(100),
    store_phone VARCHAR(50),
    store_email VARCHAR(150),
    pet_category VARCHAR(50),
    product_weight NUMERIC(8,2),
    product_color VARCHAR(50),
    product_size VARCHAR(50),
    product_brand VARCHAR(100),
    product_material VARCHAR(100),
    product_description TEXT,
    product_rating NUMERIC(3,2),
    product_reviews INT,
    product_release_date VARCHAR(50),
    product_expiry_date VARCHAR(50),
    supplier_name VARCHAR(150),
    supplier_contact VARCHAR(100),
    supplier_email VARCHAR(150),
    supplier_phone VARCHAR(50),
    supplier_address TEXT,
    supplier_city VARCHAR(100),
    supplier_country VARCHAR(100)
);

SELECT 'Таблица mock_data пересоздана' AS status;