version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: petstore-postgres
    restart: always
    environment:
      POSTGRES_DB: petstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./mock_data:/mock_data:ro
      - ./init:/docker-entrypoint-initdb.d
